version: 2
jobs:
  release:
    environment:
      NOT_CRAN: true
      PANDOC: 2.7
      R_LIBS: ~/R/Library
      _R_CHECK_CRAN_INCOMING_: TRUE
      _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
    docker:
      - image: rocker/r-base:latest
    steps:
      - restore_cache:
          keys:
            - r-pkg-cache-v2-{{ arch }}-{{ .Branch }}
            - r-pkg-cache-v2-{{ arch }}-
      - checkout
      - run:
          name: Install system dependencies
          command: bash .circleci/install-system.sh
      - run:
          name: Install pandoc
          command: bash .circleci/install-pandoc.sh $PANDOC
      - run:
          name: Install package dependencies
          command: |
            mkdir -p ~/R/Library
            Rscript .circleci/install-r-pkgs.R
      - run:
          name: Session information and installed package versions
          command: Rscript .circleci/session-info.R
      - run:
          name: Build and check
          command: bash .circleci/check.sh
      - store_artifacts:
          path: workflowr.Rcheck/
      - save_cache:
          key: r-pkg-cache-v2-{{ arch }}-{{ .Branch }}
          paths:
            - "~/R/Library"
  pandocless:
    environment:
      R_LIBS: ~/R/Library
      _R_CHECK_CRAN_INCOMING_: TRUE
      _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
    docker:
      - image: rocker/r-base:latest
    steps:
      - restore_cache:
          keys:
            - r-pkg-cache-v2-{{ arch }}-{{ .Branch }}
            - r-pkg-cache-v2-{{ arch }}-
      - checkout
      - run:
          name: Install system dependencies
          command: bash .circleci/install-system.sh
      - run:
          name: Install package dependencies
          command: |
            mkdir -p ~/R/Library
            Rscript .circleci/install-r-pkgs.R
      - run:
          name: Session information and installed package versions
          command: Rscript .circleci/session-info.R
      - run:
          name: Build and check
          command: bash .circleci/check.sh
      - store_artifacts:
          path: workflowr.Rcheck/
      - save_cache:
          key: r-pkg-cache-v2-{{ arch }}-{{ .Branch }}
          paths:
            - "~/R/Library"
  codecov:
    environment:
      NOT_CRAN: true
      PANDOC: 2.7
      R_LIBS: ~/R/Library
      _R_CHECK_CRAN_INCOMING_: TRUE
      _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
    docker:
      - image: rocker/r-base:latest
    steps:
      - restore_cache:
          keys:
            - r-pkg-cache-v2-{{ arch }}-{{ .Branch }}
            - r-pkg-cache-v2-{{ arch }}-
      - checkout
      - run:
          name: Install system dependencies
          command: bash .circleci/install-system.sh
      - run:
          name: Install pandoc
          command: bash .circleci/install-pandoc.sh $PANDOC
      - run:
          name: Install package dependencies
          command: |
            mkdir -p ~/R/Library
            Rscript .circleci/install-r-pkgs.R
      - run:
          name: Session information and installed package versions
          command: Rscript .circleci/session-info.R
      - run:
          name: Calculate code coverage
          command: Rscript -e 'covr::codecov()'
          no_output_timeout: "20m"
      - save_cache:
          key: r-pkg-cache-v2-{{ arch }}-{{ .Branch }}
          paths:
            - "~/R/Library"
workflows:
  version: 2
  all:
    jobs:
      - release
      - pandocless
      - codecov
